#!/usr/bin/env node

const fs = require('fs');

const testCases = fs.readdirSync('/ground-truths');

let score = 0;

const solutionTime = process.argv[2];

testCases.forEach((testCase) => {
  let name = testCase.split('/');
  name = name[name.length - 1].replace(/\.h5$/, '/scores.json');
  if (fs.existsSync(`/outputs/${name}`)) {
    const scores = require(`/outputs/${name}`)[0];
    score += Math.sqrt((
      scores.F1_milestones * scores.F1_milestones
      + scores.correlation * scores.correlation
      + scores.featureimp_wcor * scores.featureimp_wcor
      + scores.him * scores.him
    ) / 4);
  }
});

score /= testCases.length;

if (solutionTime) {
  score *= Math.exp(- Number(solutionTime) / testCases.length / 60000);
}

fs.writeFileSync('/outputs/AGGREGATED_SCORE', score);
